In [4]:
import torch
import torch.nn as nn
from torchvision.transforms import Compose

In [6]:
nn.Linear(in_features=10,out_features=10)
## pytorch安装成功

Linear(in_features=10, out_features=10, bias=True)

In [9]:
## 张量生成
A = torch.tensor([[1.0,1.0],[2,2]])
A

tensor([[1., 1.],
        [2., 2.]])

In [15]:
B = torch.tensor((1,2,3),dtype=torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [21]:
y = B.pow(2).sum()
y.backward()
B.grad
#只有浮点数可以进行计算梯度，其他类型不能计算张量梯度

tensor([2., 4., 6.])